WebUI/Controllers/ClientToolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections;
using static System.Net.Mime.MediaTypeNames;
using Inv.WebUI.Resources;
using System.Resources;
using System.Globalization;
using Inv.WebUI.Filter;

namespace Kids.WebUI.Controllers
{

    public class ClientToolsController : Controller
    {
  
        private struct ColumnObjectStruct
        {
            public string headerText { get; set; }
            public bool hidden { get; set; }
            public string key { get; set; }
            public string dataType { get; set; }
            public string width { get; set; }
            public bool filterable { get; set; }
        }



        #region For Search

        //public JsonResult Find(string moduleCode, string Condition, string controlName)
        //{
        //    SystemTools sys = new SystemTools();

        //    var obj = sys.SearchProperties(moduleCode, controlName);
        //    if (obj.Settings.DataSourceName == null)
        //    {
        //        return Shared.JsonObject(null);
        //    }
        //    string cols = string.Empty;

        //    List<ColumnObjectStruct> columnsObject = new List<ColumnObjectStruct>();
        //    columnsObject.Add(new ColumnObjectStruct()
        //    {
        //        dataType = "number",
        //        headerText = "",
        //        hidden = true,
        //        key = "RowIndex",
        //        width = "0"
        //    });
        //    foreach (G_SearchFormSetting column in obj.Columns)
        //    {
        //        if ((column.Language == 0) ||
        //            (SessionManager.SessionRecord.ScreenLanguage == "en" && column.Language == 2) ||
        //            (SessionManager.SessionRecord.ScreenLanguage == "ar" && column.Language == 1))
        //        {
        //            cols += "," + column.DataMember;
        //            ColumnObjectStruct colObj = new Controllers.ClientToolsController.ColumnObjectStruct();
        //            colObj.dataType = column.Datatype == 0 ? "string" : "number";

        //            if (SessionManager.SessionRecord.ScreenLanguage == "en")
        //                colObj.headerText = column.FieldTitle;
        //            else
        //                colObj.headerText = column.FieldTitleA;

        //            colObj.hidden = !column.IsReadOnly;
        //            colObj.filterable = false;
        //            colObj.key = column.DataMember;
        //            colObj.width = column.FieldWidth == 0 ? "100px" : (column.FieldWidth.ToString() + "px");

        //            columnsObject.Add(colObj);
        //        }
        //    }

        //    string tableName = obj.Settings.DataSourceName;
        //    string condition = "";

        //    if (Condition == null || Condition == "")
        //        condition = "";
        //    else
        //        condition = " Where " + Condition;

        //    string columns = cols.Substring(1);
        //    string orderBy = obj.Settings.ReturnDataPropertyName;

        //    var result = sys.Find(tableName, condition, columns, orderBy);

        //    var resultObject = new
        //    {
        //        TableName = tableName,
        //        Condition = condition,
        //        DataResult = result,
        //        Settings = obj.Settings,
        //        Columns = columnsObject

        //    };
        //    var jsonResult = Shared.JsonObject(resultObject);
        //    return jsonResult;
        //}


        //public JsonResult GetByIndex(string tableName, string Condition, int index, bool ChangePageIndex)
        //{
        //    SystemTools sys = new SystemTools();
        //    var result = sys.GetByIndex(tableName, Condition, index);
        //    var jsonResult = Shared.JsonObject(result);
        //    if (ChangePageIndex == true)
        //        SessionManager.PageIndex = index;
        //    return jsonResult;
        //}

        //public JsonResult GetIndexByUseId(string idValue, string BaseTableName, string idFieldName)
        //{
        //    SystemTools sys = new SystemTools();
        //    string _Result = sys.GetIndexByUseId(int.Parse(idValue), BaseTableName, idFieldName);
        //    return Shared.JsonObject(_Result);
        //}
        //public JsonResult GetIndexByUseCode(string idValue, string BaseTableName, string idFieldName,string condition)
        //{
        //    SystemTools sys = new SystemTools();
        //    string _Result = sys.GetIndexByUseCode(idValue, BaseTableName, idFieldName, condition);
        //    return Shared.JsonObject(_Result);
        //}

        #endregion




        //public JsonResult Refilter(string moduleCode, string Condition, string controllerName)
        //{
        //    var result = this.Find(moduleCode, Condition.Replace("Where", ""), controllerName);
        //    return result;
        //}
        //public JsonResult GetActionUrl(string actionName, string controllerName)
        //{
        //    string result = Url.Action(actionName, controllerName);
        //    return Shared.JsonObject(result);
        //}
        //public void SetValueToSession(string key, object value)
        //{
        //    Session[key] = value;
        //}
        public JsonResult GetResourceByName(string key)
        {
            SystemResource.ResourceManager.IgnoreCase = true;
            string result = SystemResource.ResourceManager.GetString(key);
            return Shared.JsonObject(result);
        }
        public JsonResult GetResourceNames(string _prefix)
        {
            Dictionary<string, string> dicResources = new Dictionary<string, string>();
            ResourceManager MyResourceClass = new ResourceManager(typeof(SystemResource));

            ResourceSet resourceSet = MyResourceClass.GetResourceSet(CultureInfo.CurrentUICulture, true, true);
            foreach (DictionaryEntry entry in resourceSet)
            {
                if (entry.Key.ToString().Contains(_prefix))
                {
                    string resourceKey = entry.Key.ToString();
                    string resourceValue = entry.Value.ToString();

                    dicResources.Add(resourceKey, resourceValue);
                }
            }
            return Shared.JsonObject(dicResources);
        }
        public JsonResult LogOut()
        {
            //Session.Clear();
            var obj = Shared.JsonObject(Url.Action("LoginIndex", "Login"));
            return obj;
        }
        //public JsonResult GetSession()
        //{
        //    var obj = new
        //    {
        //        SessionRecord = SessionManager.SessionRecord,
        //        Me = SessionManager.Me,
        //        PageIndex = SessionManager.PageIndex,
        //        ModelCount = SessionManager.ModelCount
        //    };
        //    return Shared.JsonObject(obj);
        //}
        //public void SetScreenLang(string lang)
        //{
        //    Session["ScreenLanguage"] = lang;
        //}
        //public JsonResult GetValueFromSession(string key)
        //{
        //    return Shared.JsonObject(Session[key]);
        //}

    }
}

WebUI/Views/Shared/AdminLayout.cshtml
@using Inv.WebUI.Resources
<!DOCTYPE html>

<html style="background-image:url(../../images/Background/imgadmin.jpeg)">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="UTF-8">
    <meta name="description" content="Free Web tutorials">
    <meta name="keywords" content="HTML, CSS, JavaScript">
    <meta name="author" content="John Doe">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="~/images/logokids.png">
    <title>@SystemResource.App_Home</title>
    @Styles.Render("~/Bundles/AppStyle2")
    <link id="bootstrap_rtl" href="~/Style_design/bootstrap-rtl.css" rel="stylesheet" />
    <link id="Style_Arabic" href="~/Style_design/Style_Arabic.css" rel="stylesheet" />
    @*<script src="http://code.jquery.com/jquery-3.0.0.js"></script>*@
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Style_design/js/jquery-3.4.1.js"></script>
    @Scripts.Render("~/Bundles/AppScript2")
    <script src="~/Style_design/jquery.cookie.min.js"></script>
    @Scripts.Render("~/Bundles/AppScript3Admin")
    <link href="~/Style_design/Stylelayout.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        body {
            font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
            font-size: 13px;
            line-height: 1.42857143;
            color: #333;
            background-color: unset;
        }
        .stfooter {
            margin: -15px -12px;
        }

        #btnclosefooter {
            margin: 16px -41px;
        }

        #btnclosefooter {
            position: absolute;
            z-index: 25;
            cursor: pointer;
            border-radius: 30px;
            border: solid 2px;
            background-color: #0b6ba2;
            color: #fff;
            left: 3%;
        }

        .stfooter {
            position: absolute;
            background-color: rgba(0, 0, 0, 0.7);
            height: 44px;
            /* width: 50%; */
            display: block;
            margin: 10px 0px 0px 16px;
            border-radius: 20px;
            z-index: 999;
            color: white;
            left: 5%;
        }
    </style>
</head>
<body>
    <div id="btnclosefooter">
        <i id="chevron" style="font-size: 27px" class="glyphicon glyphicon-chevron-right"></i>
        <i class=" glefbtnclosefooter" style="font-size: 25px"> اعدادات </i>

    </div>
    <div id="footer" class="stfooter">
        <div  id="displaydiv" class="col-lg-12 display_none" style="top: 3px">
                 </button>
            <a href="/Home/AdminBarIndex">
                <span class="glyphicon glyphicon-floppy-saved">
                    <button id="" type="button" class="btn btn-success   ">
                        اعدادات الفرع   <span class="glyphicon glyphicon-floppy-saved"></span>
                    </button>
                </span>
            </a>
            <a href="/Home/AdminCompIndex">
                <span class="glyphicon glyphicon-floppy-saved">
                    <button id="" type="button" class="btn btn-success   ">
                        اعدادات الشركة   <span class="glyphicon glyphicon-floppy-saved"></span>
                    </button>
                </span>
            </a>




            <i id="chevron2" style="font-size: 30px;float:right" class="glyphicon glyphicon-hand-left display_none"></i>

        </div>
    </div>
    <div>
        @RenderBody()
    </div>
    <div class="modal fade" id="user_setting" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">@SystemResource.App_UserSetting </h4>
                </div>
                <div class="user_2">
                    <form class="form-horizontal">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">@SystemResource.App_OldPassword </label>
                            <div class="col-sm-8">
                                <input type="password" class="form-control" id="txtOldPassword">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-3 control-label"> @SystemResource.App_NewPassword</label>
                            <div class="col-sm-8">
                                <input type="password" class="form-control" id="txtNewPassword">
                            </div>
                        </div>
                    </form>
                    <div class="modal-footer">
                        <button type="button" id="btnChangePassword" class="btn btn-danger">@SystemResource.App_Confirm </button>
                        <button type="button" class="btn btn-primary btn_back">@SystemResource.App_Return</button>
                        <button type="button" class="btn btn-warning" data-dismiss="modal">@SystemResource.App_Close </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="glyphicon glyphicon-arrow-up	"></i></a>
    <input type="hidden" id="GetActionUrl" name="name" value="@Url.Action("GetActionUrl","ClientTools")" />
    <input type="hidden" id="ModelPreview" name="name" value="" />
    <input type="hidden" id="SearchControlName" name="name" value="" />
    <div class="modal fade messagealert" id="MessageBoxDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="MessageBoxTitle">حذف!!</h4>
                </div>
                <div class="modal-body" style="max-height:200px; overflow:auto;">
                    <div class="col-xs-7"> <h3 id="MessageBoxMessage">هل تريد حقا الحذف ؟</h3></div>
                    <div class="col-xs-5 text-center">
                        <i class="glyphicon btn-danger"></i>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="MessageBoxOk" class="btn btn-danger">@SystemResource.App_Confirm</button>
                    <button type="button" id="MessageBoxCancel" class="btn btn-warning" data-dismiss="modal">إلغاء</button>
                </div>
            </div>
        </div>
    </div>
    <div class="help-pop modal fade in" id="myModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="myModalLabel">@SystemResource.App_Help</h4>
                </div>
                <div class="modal-body content content-8" id="modalHelpRep">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-warning" data-dismiss="modal">@SystemResource.App_Close</button>
                </div>
            </div>
        </div>
    </div>
    <div id="SearchBox" class=" fade styleserch" style="display:none;z-index:999999999;">
        <div style="background-color:#ef6603!important; position:absolute;top:0px;left:0px;width:100%;height:40px;cursor:move;border-top-right-radius: 13px!important;border-top-left-radius: 13px!important;">
            <input type="button" onclick="$('#SearchBox').modal('hide');" id="btnCloseSearch" name="name" value="x" class="btn colose_lay_btn btn-danger" style="height: 40px;
              width: 38px;font-size: 20px;float: left;border-color: #ef6603!important;background-color: #ef6603!important;" />
            <h4 id="searchTitle" class="col-xs-3" style="color: #fff;line-height: 36px;text-align:right"></h4>
        </div>
        <div style="overflow-x:scroll;overflow-y:scroll;padding-left: 1%; margin-top:20px;width:100%;left:0px;left: 0px; position: absolute; width: 100%; height: 85%;">
            <div id="tableDiv" class="table table-bordered table-hover" style="width:100%;"></div>
        </div>
    </div>
    <div id="caret_script" style="display:none!important">
    </div>
    @*<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>*@
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    @Scripts.Render("~/Bundles/AppScript4")
    <script>

        $('#lepcompinformtion').on('click', function () {
            $('#divcompinformtion').toggleClass('showdiv');
            $('#spanlepcompinformtion').toggleClass('fa-caret-left');
            $('#spanlepcompinformtion').toggleClass('fa-caret-down');
        });
        $('#lepnotifications').on('click', function () {
            $('#divnotifications').toggleClass('showdiv');
            $('#spanlepnotifications').toggleClass('fa-caret-left');
            $('#spanlepnotifications').toggleClass('fa-caret-down');
        });
        $('#lepsystem').on('click', function () {
            $('#divsystem').toggleClass('showdiv');
            $('#spanlepsystem').toggleClass('fa-caret-left');
            $('#spanlepsystem').toggleClass('fa-caret-down');
        });
        $(document).ready(function () {

            $("#btnclosefooter").click(function () {
                $("#displaydiv").removeClass("display_none");
                $("#btnclosefooter").addClass("display_none");
                $("#chevron2").removeClass("display_none");
                $("#footer").animate({ width: '500px', opacity: '0.8' }, "slow");

                $("#chevron").toggleClass("glyphicon-hand-right");
                $("#chevron").toggleClass("glyphicon-chevron-left");


            });

            $("#chevron2").click(function () {
                $("#displaydiv").addClass("display_none");
                $("#btnclosefooter").removeClass("display_none");
                $("#footer").animate({ width: '0px', opacity: '0' }, "slow");

                $("#chevron").toggleClass("glyphicon-hand-right");
                $("#chevron").toggleClass("glyphicon-chevron-left");


            });

        });
    </script>
</body>
</html>

WebUI/Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Free Web tutorials">
    <meta name="keywords" content="HTML, CSS, JavaScript">
    <meta name="author" content="John Doe">
    <meta name="viewport" content="width=device-width">
    <meta name="viewport" content="initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SmartERP</title>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Style_design/js/jquery-3.4.1.js"></script>
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/New_Design/Login_v1/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/New_Design/Login_v1/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/New_Design/Login_v1/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/New_Design/Login_v1/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/New_Design/Login_v1/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/New_Design/Login_v1/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/New_Design/Login_v1/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/New_Design/Login_v1/css/main.css">
    <!--===============================================================================================-->

</head>
<body>
    <script src="~/ClientApp/App.js"></script>
    <script src="~/ClientApp/SystemTools.js"></script>
    <script src="~/ClientApp/Entities.js"></script>
    <script src="~/ClientApp/Shared.js"></script>
    <script src="~/ClientApp/AjaxCaller.js"></script>

    <div>
        @RenderBody()
    </div>

    @*<script src="~/js/waitMe.js"></script>
        <script type="text/javascript" src="~/login/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/login/js/login.js"></script>*@

   

    <!--.............................clock...........................-->
  

    <!--===============================================================================================-->
    <script src="~/New_Design/Login_v1/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/New_Design/Login_v1/vendor/bootstrap/js/popper.js"></script>
    <script src="~/New_Design/Login_v1/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/New_Design/Login_v1/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/New_Design/Login_v1/vendor/tilt/tilt.jquery.min.js"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
    <script src="~/New_Design/Login_v1/js/main.js"></script>


    @*<script src="~/login/js/rAF.js"></script>
        <script src="~/login/js/demo-2.js"></script>*@

    <input type="hidden" id="GetActionUrl" name="name" value="@Url.Action("GetActionUrl","ClientTools")" />
</body>
</html>

WebUI/Views/Shared/Popup.cshtml
@using Inv.WebUI.Resources
@*//eslam 2 nov 2020*@

<html>
<head>
  
</head>

<body>

    <div class="modal fade" id="PopupDialog" role="dialog">
        <div class="modal-dialog">

            <div class="modal-content">
                <div id="PopupBody" class=" modal-body col-lg-12 col-xs-12 ">


                </div>
            </div>
        </div>
    </div>

 
 
</body>
</html>

WebUI/Views/Shared/Popuppicture.cshtml
@using Inv.WebUI.Resources
@*//eslam 2 nov 2020*@

<html>
<head>

    <link href="~/Scripts/JsGrid/jsgrid.min.css" rel="stylesheet" />
    <link href="~/Scripts/JsGrid/jsgrid-theme.min.css" rel="stylesheet" />
    <link href="~/Scripts/jsgrid/jsgrid-theme.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />


</head>

<body>

    <div class="modal fade" id="PopupDialogpicture" role="dialog">
        <div class="modal-dialog">

            <div class="modal-content">
                <div id="Bodypicture" class=" modal-body col-lg-12 col-xs-12 " style="width: 80%;">
                    <button style="margin-top: 3px;" type="button" class="close" data-dismiss="modal">&times;</button>


                </div>
            </div>
        </div>
    </div>


    @*datatable For search*@

    <script src="~/Style_design/js/vendor/jquery-1.11.3.min.js"></script>
    <script src="~/ClientApp/JsGrid.js"></script>
    <script src="~/Scripts/jsgrid/jsgrid.js"></script>
    @*<script src="~/js/my_js.js"></script>*@
    <script src="~/js/bootstrap.min.js"></script>

    <!-- bootstrap JS
    ============================================ -->
    <script src="~/Style_design/js/bootstrap.min.js"></script>
    <!-- meanmenu JS
    ============================================ -->
    <script src="~/Style_design/js/jquery.meanmenu.js"></script>
    <!-- mCustomScrollbar JS
    ============================================ -->
    <script src="~/Style_design/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <!-- sticky JS
    ============================================ -->
    <script src="~/Style_design/js/jquery.sticky.js"></script>
    <!-- scrollUp JS
    ============================================ -->
    <script src="~/Style_design/js/jquery.scrollUp.min.js"></script>
    <!-- counterup JS
    ============================================ -->
    <script src="~/Style_design/js/counterup/jquery.counterup.min.js"></script>
    <script src="~/Style_design/js/counterup/waypoints.min.js"></script>
    <!-- dropzone JS
    ============================================ -->
    <script src="~/Style_design/js/dropzone.js"></script>
    <!-- multiple email JS
    ============================================ -->
    <script src="~/Style_design/js/multiple-email/multiple-email-active.js"></script>
    <!-- summernote JS
    ============================================ -->
    <script src="~/Style_design/js/summernote.min.js"></script>
    <script src="~/Style_design/js/summernote-active.js"></script>
    <!-- main JS
    ============================================ -->
    <script src="~/Style_design/js/vendor/modernizr-2.8.3.min.js"></script>
    @*End Data table*@
</body>
</html>

WebUI/Views/Shared/_ErrorPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script>
        $(document).ready(function () {
            var error = getParameterByName("err");
            if (error != null) {
                $("#divError").css("display", "");
                $("#divError").text(error);
            }
        });

        function getParameterByName(name, url) {
            if (!url) url = window.location.href;
            name = name.replace(/[\[\]]/g, "\\$&");
            var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
                results = regex.exec(url);
            if (!results) return null;
            if (!results[2]) return '';
            return decodeURIComponent(results[2].replace(/\+/g, " "));
        }
    </script>
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <div id="divError" style="display:none;">

    </div>
</body>
</html>